# Define 'Secret' to store db-credentials 
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials # Name of the 'Secret'
data:
  username: c2lkeg==  # base64 encoded 'Secret' username
  password: c2lkendveno= # base64 encoded 'Secret' password
