# Define 'Secret' to store 'root' user Credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials # Name of the Secret
data:
  username: ZW50eXRsZQ==  # base64 encoded 'root' username
  password: RW50eXRsZSMyMDIw # base64 encoded 'root' password